# Generated by Django 3.2.18 on 2023-03-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default='gWt1xdQO2T6D', max_length=12, unique=True),
        ),
    ]
