# Generated by Django 3.2.18 on 2023-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_horse_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default='6pguUG1ek4mF', max_length=12, unique=True),
        ),
    ]
