# Generated by Django 3.2.18 on 2023-03-25 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_horse_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default='ONp5z61ZDQS0', max_length=12, unique=True),
        ),
    ]
