# Generated by Django 3.2.18 on 2023-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230325_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default='5YKLLn47gXCV', max_length=12, unique=True),
        ),
    ]
