# Generated by Django 3.2.18 on 2023-03-17 04:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_horse_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.horse_image_file_path),
        ),
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default='a9dbZqMCW1Is', max_length=12, unique=True),
        ),
    ]
