# Generated by Django 3.2.18 on 2023-04-04 07:55

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_horse_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='api_key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 12}), max_length=12, unique=True),
        ),
    ]
